version: '3.5'

services:
  blog:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: blog
    image: blog
    ports:
      - 8000:8000
    depends_on:
      blog-postgres:
        condition: service_healthy
    # command: >
    #   /bin/sh -c "alembic upgrade head && alembic revision --autogenerate -m 'Initial migration' && uvicorn blog.main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - blog-network

  blog-postgres:
    container_name: blog-postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - blog-pg-data:/var/lib/postgresql/data
    image: postgres:15-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 10
    networks:
      - blog-network

volumes:
  blog-pg-data: 
    name: blog-pg-data

networks:
  blog-network:
    driver: bridge
