"""Initial migration

Revision ID: b0b12f1806e8
Revises: 
Create Date: 2024-10-26 20:10:34.126350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0b12f1806e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogs', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('blogs', 'body',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('blogs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_categories_name', table_name='categories')
    op.create_unique_constraint(None, 'categories', ['name'])
    op.drop_column('categories', 'content')
    op.drop_column('comments', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('content', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'categories', type_='unique')
    op.create_index('ix_categories_name', 'categories', ['name'], unique=True)
    op.alter_column('blogs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('blogs', 'body',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('blogs', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
